services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: streaming-client
    ports:
      - "5174:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_PROXY_TARGET=http://server:4000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: streaming-server
    ports:
      - "4001:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/streaming
      - REDIS_URL=redis://host.docker.internal:6379
      - NODE_ENV=development
      - JWT_ACCESS_SECRET=your-super-secret-access-key-change-in-production-min-32-chars
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production-min-32-chars
      - CLIENT_URL=http://localhost:5174
      - TMDB_API_KEY=1a68b0b3695c7a1b3d40e733f9216c0f
      - MIXDROP_EMAIL=abdallahalfeky18@gmail.com
      - MIXDROP_KEY=4EVGd13ASvIzitK4RW
      - IMGBB_API_KEY=b862099c9905e0f993edfc8a7c011e95
    extra_hosts:
      - "host.docker.internal:host-gateway"
